Repository kgu-developers/aics-server, pull requests merged in 2024-10, with the labels that each got.

#3 feature/#1 멀티모듈 아키텍처 기반 프로젝트 초기 세팅
  .gitignore
  aics-apis/aics-api/build.gradle
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/AicsApiApplication.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/InfraConfig.java
  aics-apis/aics-api/src/main/resources/application-dev.yml
  aics-apis/aics-api/src/main/resources/application-local.yml
  aics-apis/aics-api/src/main/resources/application-prod.yml
  aics-apis/aics-api/src/main/resources/application.yml
  aics-core/aics-common/build.gradle
  aics-core/aics-common/src/main/java/kgu/developers/core/common/config/SecurityConfig.java
  aics-core/aics-common/src/main/java/kgu/developers/core/common/domain/BaseTimeEntity.java
  aics-core/aics-common/src/main/java/kgu/developers/core/common/exception/CustomException.java
  aics-core/aics-common/src/main/java/kgu/developers/core/common/exception/ExceptionCode.java
  aics-core/aics-common/src/main/java/kgu/developers/core/common/exception/ExceptionResponse.java
  aics-core/aics-common/src/main/java/kgu/developers/core/common/exception/GlobalExceptionCode.java
  aics-core/aics-common/src/main/java/kgu/developers/core/common/exception/GlobalExceptionHandler.java
  aics-core/aics-common/src/main/java/kgu/developers/core/common/response/PageableResponse.java
  aics-core/aics-domain/build.gradle
  aics-core/aics-infra/build.gradle
  aics-core/aics-infra/src/main/java/kgu/developers/core/infra/AicsConfig.java
  aics-core/aics-infra/src/main/java/kgu/developers/core/infra/AicsConfigGroup.java
  aics-core/aics-infra/src/main/java/kgu/developers/core/infra/AicsConfigImportSelector.java
  aics-core/aics-infra/src/main/java/kgu/developers/core/infra/EnableAicsConfig.java
  aics-core/aics-infra/src/main/java/kgu/developers/core/infra/config/JpaAuditingConfig.java
  aics-core/aics-infra/src/main/java/kgu/developers/core/infra/config/JpaConfig.java
  aics-core/aics-infra/src/main/java/kgu/developers/core/infra/config/PropertiesConfig.java
  aics-core/aics-infra/src/main/java/kgu/developers/core/infra/config/SwaggerConfig.java
  aics-global-utils/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: ✨feature

#6 refactor/ gitkeep 파일 추가 및 InfraConfig config 하위로 이동
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/config/InfraConfig.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/.gitkeep
  aics-global-utils/src/main/java/kgu/developers/globalutils/.gitkeep
Labels: 🔨refactor

#10 feature/#4 User 엔티티 생성
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/.gitkeep
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/Gender.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/Grade.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/Role.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/Status.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/User.java
Labels: ✨feature

#12 refactor/#4 User 생성 시 정적 팩토리 메서드 패턴 사용하도록 변경
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/Role.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/User.java
Labels: 🔨refactor

#11 feature/#5 Major 엔티티 생성
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/major/Major.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/User.java
Labels: ✨feature

#14 feature/#8 post entity 생성
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/post/Category.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/post/Post.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/User.java
Labels: ✨feature

#15 refactor/연관관계 매핑 전략 변경 및 사소한 수정
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/comment/Comment.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/major/Major.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/post/Post.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/User.java
Labels: 🔨refactor

#21 refactor/#18 예외 응답 반환 시 Code만 반환하도록 변경
  aics-core/aics-common/src/main/java/kgu/developers/core/common/exception/ExceptionResponse.java
Labels: 🔨refactor

#20 feature/#17 유저 회원가입 api 구현
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/config/InfraConfig.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/application/UserService.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/UserController.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/exception/UserExceptionCode.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/exception/UserPersonalIdDuplicateException.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/request/UserCreateRequest.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/response/UserPersistResponse.java
  aics-core/aics-common/src/main/java/kgu/developers/core/common/config/SecurityConfig.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/comment/Comment.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/post/Post.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/Gender.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/Grade.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/Role.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/Status.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/User.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/domain/Gender.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/domain/Grade.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/domain/Role.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/domain/Status.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/domain/User.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/domain/UserRepository.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/infrastructure/JpaUserRepository.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/infrastructure/UserRepositoryImpl.java
Labels: ✨feature

#22 feature/#16 전공 생성 API 구현
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/AicsApiApplication.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/application/MajorService.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/presentation/MajorController.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/presentation/exception/MajorDuplicatedException.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/presentation/exception/MajorExceptionCode.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/presentation/exception/MajorNotFoundException.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/presentation/request/MajorCreateRequest.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/presentation/response/MajorPersistResponse.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/application/UserService.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/major/domain/Major.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/major/domain/MajorRepository.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/major/infrastructure/JpaMajorRepository.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/major/infrastructure/MajorRepositoryImpl.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/domain/User.java
Labels: ✨feature

#26 feature/#25 jwt 토큰 기반 로그인 API 구현
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/auth/application/AuthService.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/auth/presentation/AuthController.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/auth/presentation/exception/AuthExceptionCode.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/auth/presentation/exception/InvalidPasswordException.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/auth/presentation/request/LoginRequest.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/auth/presentation/response/TokenResponse.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/application/UserService.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/UserController.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/exception/UserExceptionCode.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/exception/UserNotAuthenticatedException.java
  aics-apis/aics-api/src/main/resources/application.yml
  aics-core/aics-common/src/main/java/kgu/developers/core/common/auth/filter/TokenAuthenticationFilter.java
  aics-core/aics-common/src/main/java/kgu/developers/core/common/auth/jwt/JwtProperties.java
  aics-core/aics-common/src/main/java/kgu/developers/core/common/auth/jwt/TokenProvider.java
  aics-core/aics-common/src/main/java/kgu/developers/core/common/config/SecurityConfig.java
  aics-core/aics-common/src/main/java/kgu/developers/core/common/exception/ExceptionResponse.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/domain/User.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/domain/UserRepository.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/exception/UserDomainExceptionCode.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/exception/UserNotFoundException.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/infrastructure/JpaUserRepository.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/infrastructure/UserRepositoryImpl.java
Labels: ✨feature

#27 feature/#24 회원 정보 수정 API 구현
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/application/UserService.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/UserController.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/exception/UserEmailDuplicateException.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/exception/UserExceptionCode.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/exception/UserPersonalIdDuplicateException.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/exception/UserPhoneNumberDuplicateException.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/request/UserCreateRequest.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/request/UserUpdateRequest.java
  aics-core/aics-common/src/main/java/kgu/developers/core/common/config/SecurityConfig.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/domain/User.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/domain/UserRepository.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/infrastructure/JpaUserRepository.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/infrastructure/UserRepositoryImpl.java
Labels: ✨feature

#30 refactor/#28 스웨거 응답 스키마 포맷 통일 및 사소한 수정
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/auth/presentation/AuthController.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/application/MajorService.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/presentation/MajorController.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/application/UserService.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/UserController.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/request/UserCreateRequest.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/major/domain/MajorRepository.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/major/infrastructure/JpaMajorRepository.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/major/infrastructure/MajorRepositoryImpl.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/domain/User.java
Labels: 🔨refactor

#29 feature/#23 회원 조회 마이페이지 API
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/auth/presentation/AuthController.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/auth/presentation/request/LoginRequest.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/application/UserService.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/UserController.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/request/UserCreateRequest.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/response/UserDetailResponse.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/domain/User.java
Labels: ✨feature

#33 feature/#31 유저 엔티티 수정
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/auth/application/AuthService.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/auth/presentation/request/LoginRequest.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/application/MajorService.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/presentation/MajorController.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/presentation/exception/MajorDuplicatedException.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/presentation/exception/MajorExceptionCode.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/presentation/request/MajorCreateRequest.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/major/presentation/response/MajorPersistResponse.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/application/UserService.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/exception/UserExceptionCode.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/exception/UserIdDuplicateException.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/exception/UserPersonalIdDuplicateException.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/request/UserCreateRequest.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/request/UserUpdateRequest.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/response/UserDetailResponse.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/response/UserPersistResponse.java
  aics-core/aics-common/src/main/java/kgu/developers/core/common/auth/jwt/TokenProvider.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/major/domain/Major.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/major/domain/MajorRepository.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/major/infrastructure/JpaMajorRepository.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/major/infrastructure/MajorRepositoryImpl.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/domain/Grade.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/domain/Major.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/domain/Role.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/domain/Status.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/domain/User.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/domain/UserRepository.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/infrastructure/JpaUserRepository.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/infrastructure/UserRepositoryImpl.java
Labels: 🔨refactor

#35 refactor/#32 회원가입 API 수정
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/application/UserService.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/exception/UserEmailDuplicateException.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/exception/UserPhoneNumberDuplicateException.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/request/UserCreateRequest.java
Labels: 🔨refactor

#38 Feature/#36 Post 엔티티 수정 및 게시글 작성 API 구현
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/post/application/PostService.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/post/presentation/PostController.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/post/presentation/request/PostCreateRequest.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/post/presentation/response/PostPersistResponse.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/post/Post.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/post/PostRepository.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/post/infrastructure/JpaPostRepository.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/post/infrastructure/PostRepositoryImpl.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/domain/User.java
Labels: ✨feature

#40 feature/#34 파일 업로드 기능
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/AicsApiApplication.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/auth/presentation/request/LoginRequest.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/file/application/FileService.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/file/presentation/FileController.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/file/presentation/exception/FileExceptionCode.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/file/presentation/exception/FileSavingException.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/file/presentation/response/FilePersistResponse.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/UserController.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/request/UserCreateRequest.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/file/domain/FileEntity.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/file/domain/FileRepository.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/file/infrastructure/FileRepositoryImpl.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/file/infrastructure/JpaFileRepository.java
  aics-global-utils/src/main/java/kgu/developers/globalutils/file/FileHandler.java
Labels: ✨feature

#39 feature/#37 게시판 페이징 조회 API 구현
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/post/application/PostService.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/post/presentation/PostController.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/post/presentation/response/PostSummaryPageResponse.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/post/presentation/response/PostSummaryResponse.java
  aics-apis/aics-api/src/main/java/kgu/developers/apis/api/user/presentation/UserController.java
  aics-core/aics-common/src/main/java/kgu/developers/core/common/response/PageableResponse.java
  aics-core/aics-common/src/main/java/kgu/developers/core/common/response/PaginatedListResponse.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/comment/Comment.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/post/PostRepository.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/post/domain/Category.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/post/domain/Post.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/post/domain/PostRepository.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/post/infrastructure/JpaPostRepository.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/post/infrastructure/PostRepositoryImpl.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/post/infrastructure/QueryPostRepository.java
  aics-core/aics-domain/src/main/java/kgu/developers/core/domain/user/domain/User.java
  aics-core/aics-infra/src/main/java/kgu/developers/core/infra/config/JpaConfig.java
Labels: ✨feature

#47 feature/#43 게시글 조회 기능
  aics-api/src/main/java/kgu/developers/api/file/presentation/response/FileResponse.java
  aics-api/src/main/java/kgu/developers/api/post/application/PostService.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/PostController.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/exception/PostExceptionCode.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/exception/PostNotFoundException.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/request/PostRequest.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/response/CommentPostDetailResponse.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/response/PostDetailResponse.java
  aics-domain/src/main/java/kgu/developers/domain/post/domain/Post.java
  aics-domain/src/main/java/kgu/developers/domain/post/domain/PostRepository.java
  aics-domain/src/main/java/kgu/developers/domain/post/infrastructure/JpaPostRepository.java
  aics-domain/src/main/java/kgu/developers/domain/post/infrastructure/PostRepositoryImpl.java
  aics-domain/src/main/java/kgu/developers/domain/post/infrastructure/QueryPostRepository.java
  aics-domain/src/main/java/kgu/developers/domain/user/domain/Major.java
  aics-global-utils/src/main/java/kgu/developers/globalutils/file/FileHandler.java
Labels: ✨feature

#49 feature/#44 게시글 삭제 기능
  aics-api/src/main/java/kgu/developers/api/post/application/PostService.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/PostController.java
  aics-common/src/main/java/kgu/developers/common/domain/BaseTimeEntity.java
  aics-domain/src/main/java/kgu/developers/domain/post/domain/Post.java
  aics-domain/src/main/java/kgu/developers/domain/post/infrastructure/QueryPostRepository.java
Labels: ✨feature

#50 feature/#7 AOP와 인터셉터를 이용한 로깅 시스템 구축
  aics-api/src/main/java/kgu/developers/api/aspect/ExceptionLoggingAspect.java
  aics-api/src/main/java/kgu/developers/api/aspect/ServerErrorLoggingAspect.java
  aics-api/src/main/java/kgu/developers/api/post/application/PostService.java
  aics-common/src/main/java/kgu/developers/common/config/WebConfig.java
  aics-common/src/main/java/kgu/developers/common/interceptor/LoggingInterceptor.java
  aics-global-utils/src/main/java/kgu/developers/globalutils/.gitkeep
  aics-global-utils/src/main/java/kgu/developers/globalutils/annotation/NoLogging.java
  aics-global-utils/src/main/java/kgu/developers/globalutils/logging/HttpReqResUtils.java
  aics-global-utils/src/main/java/kgu/developers/globalutils/logging/LoggingUtils.java
Labels: ✨feature, 🔨refactor

#51 feature/#45-게시글-고정-상태-토글-api
  aics-api/src/main/java/kgu/developers/api/post/application/PostService.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/PostController.java
  aics-domain/src/main/java/kgu/developers/domain/post/domain/Post.java
  aics-domain/src/main/java/kgu/developers/domain/post/infrastructure/QueryPostRepository.java
Labels: ✨feature, 🔨refactor

#55 refactor/#54 게시글 관련 API 사소한 수정
  aics-api/src/main/java/kgu/developers/api/comment/application/.gitkeep
  aics-api/src/main/java/kgu/developers/api/comment/presentation/request/.gitkeep
  aics-api/src/main/java/kgu/developers/api/comment/presentation/response/CommentListResponse.java
  aics-api/src/main/java/kgu/developers/api/comment/presentation/response/CommentResponse.java
  aics-api/src/main/java/kgu/developers/api/file/presentation/FileController.java
  aics-api/src/main/java/kgu/developers/api/post/application/PostService.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/PostController.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/response/PostDetailResponse.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/response/PostSummaryPageResponse.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/response/PostSummaryResponse.java
  aics-domain/src/main/java/kgu/developers/domain/post/domain/Post.java
  aics-domain/src/main/java/kgu/developers/domain/post/infrastructure/QueryPostRepository.java
Labels: 🔨refactor

#63 feature/#61 게시글 삭제 스케줄링 api 구현
  aics-api/src/main/java/kgu/developers/api/AicsApiApplication.java
  aics-api/src/main/java/kgu/developers/api/post/application/PostService.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/PostController.java
  aics-domain/src/main/java/kgu/developers/domain/post/domain/PostRepository.java
  aics-domain/src/main/java/kgu/developers/domain/post/infrastructure/PostRepositoryImpl.java
  aics-domain/src/main/java/kgu/developers/domain/post/infrastructure/QueryPostRepository.java
Labels: ✨feature

#62 feature/#57 댓글 생성 기능
  aics-api/src/main/java/kgu/developers/api/comment/application/.gitkeep
  aics-api/src/main/java/kgu/developers/api/comment/application/CommentService.java
  aics-api/src/main/java/kgu/developers/api/comment/presentation/CommentController.java
  aics-api/src/main/java/kgu/developers/api/comment/presentation/request/.gitkeep
  aics-api/src/main/java/kgu/developers/api/comment/presentation/request/CommentRequest.java
  aics-api/src/main/java/kgu/developers/api/comment/presentation/response/CommentListResponse.java
  aics-api/src/main/java/kgu/developers/api/comment/presentation/response/CommentPersistResponse.java
  aics-api/src/main/java/kgu/developers/api/comment/presentation/response/CommentResponse.java
  aics-api/src/main/java/kgu/developers/api/post/application/PostService.java
  aics-domain/src/main/java/kgu/developers/domain/comment/domain/Comment.java
  aics-domain/src/main/java/kgu/developers/domain/comment/domain/CommentRepository.java
  aics-domain/src/main/java/kgu/developers/domain/comment/infrastructure/CommentRepositoryImpl.java
  aics-domain/src/main/java/kgu/developers/domain/comment/infrastructure/JpaCommentRepository.java
  aics-domain/src/main/java/kgu/developers/domain/post/domain/Post.java
Labels: ✨feature

#64 feature/#60 댓글 수정 기능
  aics-api/src/main/java/kgu/developers/api/comment/application/CommentService.java
  aics-api/src/main/java/kgu/developers/api/comment/presentation/CommentController.java
  aics-api/src/main/java/kgu/developers/api/comment/presentation/exception/CommentExceptionCode.java
  aics-api/src/main/java/kgu/developers/api/comment/presentation/exception/CommentNotFoundException.java
  aics-domain/src/main/java/kgu/developers/domain/comment/domain/Comment.java
  aics-domain/src/main/java/kgu/developers/domain/comment/domain/CommentRepository.java
  aics-domain/src/main/java/kgu/developers/domain/comment/infrastructure/CommentRepositoryImpl.java
Labels: ✨feature

#66 feature/#59 댓글 삭제 api 구현
  aics-api/src/main/java/kgu/developers/api/comment/application/CommentService.java
  aics-api/src/main/java/kgu/developers/api/comment/presentation/CommentController.java
  aics-api/src/main/java/kgu/developers/api/comment/presentation/request/CommentListRequest.java
  aics-domain/src/main/java/kgu/developers/domain/comment/domain/CommentRepository.java
  aics-domain/src/main/java/kgu/developers/domain/comment/infrastructure/CommentRepositoryImpl.java
  aics-domain/src/main/java/kgu/developers/domain/comment/infrastructure/QueryCommentRepository.java
  aics-domain/src/main/java/kgu/developers/domain/post/domain/Post.java
  aics-domain/src/main/java/kgu/developers/domain/post/infrastructure/QueryPostRepository.java
Labels: ✨feature
