Repository kgu-developers/aics-server, pull requests merged in 2024-12, with the labels that each got.

#121 feature/#118 DB 쿼리 작성
  aics-api/src/main/resources/db/data.sql
  aics-api/src/main/resources/db/schema.sql
Labels: ✨feature

#124 feature/#122 연구실 테스트 코드 작성
  aics-api/src/main/java/kgu/developers/api/lab/application/LabService.java
  aics-api/src/main/java/kgu/developers/api/lab/presentation/request/LabRequest.java
  aics-api/src/testFixtures/java/lab/application/LabServiceTest.java
  aics-api/src/testFixtures/java/lab/presentation/LabControllerTest.java
  aics-domain/src/testFixtures/java/lab/application/LabServiceTest.java
  aics-domain/src/testFixtures/java/lab/domain/LabDomainTest.java
  aics-domain/src/testFixtures/java/mock/FakeLabRepository.java
Labels: ✨feature

#128 feature/#127 about domain, service testcode 구현
  aics-api/src/main/java/kgu/developers/api/about/application/AboutService.java
  aics-api/src/main/java/kgu/developers/api/about/presentation/AboutController.java
  aics-api/src/main/java/kgu/developers/api/about/presentation/request/AboutRequest.java
  aics-api/src/main/java/kgu/developers/api/about/presentation/request/AboutUpdateRequest.java
  aics-api/src/testFixtures/java/about/application/AboutServiceTest.java
  aics-domain/src/testFixtures/java/about/application/AboutServiceTest.java
  aics-domain/src/testFixtures/java/about/domain/AboutDomainTest.java
  aics-domain/src/testFixtures/java/mock/FakeAboutRepository.java
Labels: ✨feature

#129 feature/#126 Jacoco를 사용한 테스트 커버리지 측정
  .github/workflows/pull-request-jacoco.yml
  aics-api/build.gradle
  aics-domain/build.gradle
  aics-domain/src/testFixtures/java/professor/domain/ProfessorDomainTest.java
  build.gradle
  gradle/jacoco.gradle
  lombok.config
Labels: ✨feature

#131 refactor/#130 게시글 상세 조회 시 이전, 다음 게시글 정보 추가
  aics-api/src/main/java/kgu/developers/api/post/application/PostService.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/PostController.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/response/PostDetailResponse.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/response/PostTitleResponse.java
  aics-api/src/testFixtures/java/post/application/PostServiceTest.java
  aics-common/src/main/java/kgu/developers/common/exception/GlobalExceptionHandler.java
  aics-domain/src/main/java/kgu/developers/domain/post/domain/PostRepository.java
  aics-domain/src/main/java/kgu/developers/domain/post/infrastructure/JpaPostRepository.java
  aics-domain/src/main/java/kgu/developers/domain/post/infrastructure/PostRepositoryImpl.java
  aics-domain/src/testFixtures/java/mock/FakePostRepository.java
Labels: 🔨refactor

#134 refactor/#133 Jacoco 워크플로우 이름 변경
  .github/workflows/pull-request-jacoco.yml
Labels: 🔨refactor

#136 feature/#135 codecov로 jacoco test coverage 시각화
  .github/workflows/pull-request-test-coverage.yml
  codecov.yml
Labels: ✨feature

#140 refactor/#132 파일 업로드 BL 리팩토링
  aics-api/src/main/java/kgu/developers/api/file/application/FileService.java
  aics-api/src/main/java/kgu/developers/api/file/presentation/FileController.java
  aics-api/src/main/java/kgu/developers/api/file/presentation/response/FilePathResponse.java
  aics-api/src/main/java/kgu/developers/api/file/presentation/response/FileResponse.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/response/PostDetailResponse.java
  aics-api/src/main/resources/application.yml
  aics-common/src/main/java/kgu/developers/common/auth/jwt/JwtProperties.java
  aics-common/src/main/java/kgu/developers/common/config/WebConfig.java
  aics-domain/src/main/java/kgu/developers/domain/file/domain/FileDomain.java
  aics-domain/src/main/java/kgu/developers/domain/file/domain/FileEntity.java
  aics-domain/src/main/java/kgu/developers/domain/file/exception/FileDirectoryCreationFailedException.java
  aics-domain/src/main/java/kgu/developers/domain/file/exception/FileDomainExceptionCode.java
  aics-domain/src/main/java/kgu/developers/domain/file/exception/FileNotFoundException.java
  aics-domain/src/main/java/kgu/developers/domain/file/exception/FilePathInvalidException.java
  aics-domain/src/main/java/kgu/developers/domain/file/exception/FileStoreFailedException.java
  aics-domain/src/main/java/kgu/developers/domain/file/infrastructure/FilePathProperties.java
  aics-domain/src/main/java/kgu/developers/domain/file/infrastructure/FileStorageService.java
  aics-domain/src/main/java/kgu/developers/domain/file/infrastructure/FileStorageServiceImpl.java
  aics-global-utils/src/main/java/kgu/developers/globalutils/encryption/AesUtil.java
  aics-global-utils/src/main/java/kgu/developers/globalutils/file/FileHandler.java
  aics-global-utils/src/main/java/kgu/developers/globalutils/multipart/MultipartJackson2HttpMessageConverter.java
Labels: ✨feature, 🔨refactor

#139 feature/#138 Access Token 재발급
  aics-api/src/main/java/kgu/developers/api/auth/application/AuthService.java
  aics-api/src/main/java/kgu/developers/api/auth/presentation/AuthController.java
  aics-api/src/main/java/kgu/developers/api/auth/presentation/exception/AuthExceptionCode.java
  aics-api/src/main/java/kgu/developers/api/auth/presentation/exception/TokenNotFoundException.java
  aics-api/src/main/java/kgu/developers/api/auth/presentation/request/RefreshTokenRequest.java
  aics-api/src/main/java/kgu/developers/api/auth/presentation/response/AccessTokenResponse.java
  aics-api/src/testFixtures/java/auth/application/AuthServiceTest.java
  aics-api/src/testFixtures/java/mock/TestContainer.java
  aics-domain/src/main/java/kgu/developers/domain/refreshtoken/domain/RefreshToken.java
  aics-domain/src/main/java/kgu/developers/domain/refreshtoken/domain/RefreshTokenRepository.java
  aics-domain/src/testFixtures/java/mock/FakeRefreshTokenRepository.java
  aics-domain/src/testFixtures/java/refreshtoken/domain/RefreshTokenDomainTest.java
  aics-infra/src/main/java/kgu/developers/infra/config/RedisConfig.java
  build.gradle
Labels: ✨feature

#144 refactor/#141 이슈 및 PR 템플릿 수정
  .github/ISSUE_TEMPLATE/bug.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🔨refactor

#146 fix/#145 서버 에러 로그 남지 않는 문제 픽스
  aics-api/src/main/java/kgu/developers/api/aspect/ServerErrorLoggingAspect.java
  aics-common/src/main/java/kgu/developers/common/interceptor/LoggingInterceptor.java
Labels: 🐞bug, 🔨refactor

#147 refactor/#132 확장자 검증 로직 추가 및 파일 업로드 관련 수정
  aics-api/src/main/java/kgu/developers/api/file/application/FileService.java
  aics-api/src/main/java/kgu/developers/api/file/presentation/response/FilePathResponse.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/response/PostDetailResponse.java
  aics-api/src/main/resources/application.yml
  aics-common/src/main/java/kgu/developers/common/config/SecurityConfig.java
  aics-domain/src/main/java/kgu/developers/domain/file/domain/FileEntity.java
  aics-domain/src/main/java/kgu/developers/domain/file/exception/FileDomainExceptionCode.java
  aics-domain/src/main/java/kgu/developers/domain/file/exception/NotSupportedFileExtensionException.java
  aics-domain/src/main/java/kgu/developers/domain/file/infrastructure/FilePathProperties.java
  aics-domain/src/main/java/kgu/developers/domain/file/infrastructure/FileStorageServiceImpl.java
Labels: 🔨refactor

#149 refactor/#148 codecov 테스트 결과가 develop 브랜치에 업로드되지 않는 문제 수정
  .github/workflows/pull-request-test-coverage.yml
Labels: 🐞bug, 🔨refactor

#154 refactor/#150 RTR 기법 도입
  aics-api/src/main/java/kgu/developers/api/auth/application/AuthService.java
  aics-api/src/main/java/kgu/developers/api/auth/presentation/AuthController.java
  aics-api/src/main/java/kgu/developers/api/auth/presentation/response/AccessTokenResponse.java
  aics-domain/src/main/java/kgu/developers/domain/refreshtoken/domain/RefreshToken.java
  aics-domain/src/testFixtures/java/refreshtoken/domain/RefreshTokenDomainTest.java
Labels: 🔨refactor

#153 refactor/#152 DDL 및 DML 최신화
  aics-api/src/main/resources/db/data.sql
  aics-api/src/main/resources/db/schema.sql
Labels: 🔨refactor
