Repository kgu-developers/aics-server, pull requests merged in 2024-11, with the labels that each got.

#70 refactor/#69 게시글 존재 여부 확인 및 사소한 수정
  aics-api/src/main/java/kgu/developers/api/comment/application/CommentService.java
  aics-api/src/main/java/kgu/developers/api/comment/presentation/exception/CommentExceptionCode.java
  aics-api/src/main/java/kgu/developers/api/comment/presentation/exception/CommentNotFoundException.java
  aics-api/src/main/java/kgu/developers/api/file/presentation/exception/FileExceptionCode.java
  aics-api/src/main/java/kgu/developers/api/file/presentation/exception/FileSavingException.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/exception/PostExceptionCode.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/exception/PostNotFoundException.java
Labels: 🔨refactor

#72 refactor/#71 transactional 의존성 변경
  aics-api/src/main/java/kgu/developers/api/auth/application/AuthService.java
  aics-api/src/main/java/kgu/developers/api/comment/application/CommentService.java
  aics-api/src/main/java/kgu/developers/api/post/application/PostService.java
  aics-api/src/main/java/kgu/developers/api/user/application/UserService.java
Labels: 🔨refactor

#76 feature/#74 연구실 crud api 구현
  aics-api/src/main/java/kgu/developers/api/lab/application/LabService.java
  aics-api/src/main/java/kgu/developers/api/lab/presentation/LabController.java
  aics-api/src/main/java/kgu/developers/api/lab/presentation/exception/LabExceptionCode.java
  aics-api/src/main/java/kgu/developers/api/lab/presentation/exception/LabNotFoundException.java
  aics-api/src/main/java/kgu/developers/api/lab/presentation/request/LabRequest.java
  aics-api/src/main/java/kgu/developers/api/lab/presentation/response/LabDetailResponse.java
  aics-api/src/main/java/kgu/developers/api/lab/presentation/response/LabListResponse.java
  aics-api/src/main/java/kgu/developers/api/lab/presentation/response/LabPersistResponse.java
  aics-domain/src/main/java/kgu/developers/domain/lab/domain/Lab.java
  aics-domain/src/main/java/kgu/developers/domain/lab/domain/LabRepository.java
  aics-domain/src/main/java/kgu/developers/domain/lab/infrastructure/JpaLabRepository.java
  aics-domain/src/main/java/kgu/developers/domain/lab/infrastructure/LabRepositoryImpl.java
Labels: ✨feature

#75 feature/#73 교수 CRUD API 구현
  aics-api/src/main/java/kgu/developers/api/professor/application/ProfessorService.java
  aics-api/src/main/java/kgu/developers/api/professor/presentation/ProfessorController.java
  aics-api/src/main/java/kgu/developers/api/professor/presentation/exception/ProfessorExceptionCode.java
  aics-api/src/main/java/kgu/developers/api/professor/presentation/exception/ProfessorNotFoundException.java
  aics-api/src/main/java/kgu/developers/api/professor/presentation/request/ProfessorRequest.java
  aics-api/src/main/java/kgu/developers/api/professor/presentation/response/ProfessorListResponse.java
  aics-api/src/main/java/kgu/developers/api/professor/presentation/response/ProfessorPersistResponse.java
  aics-api/src/main/java/kgu/developers/api/professor/presentation/response/ProfessorResponse.java
  aics-common/src/main/java/kgu/developers/common/config/SecurityConfig.java
  aics-domain/src/main/java/kgu/developers/domain/professor/domain/Professor.java
  aics-domain/src/main/java/kgu/developers/domain/professor/domain/ProfessorRepository.java
  aics-domain/src/main/java/kgu/developers/domain/professor/infrastructure/JpaProfessorRepository.java
  aics-domain/src/main/java/kgu/developers/domain/professor/infrastructure/ProfessorRepositoryImpl.java
Labels: ✨feature

#80 chore/#79 종속성 관리를 위한 dependabot 적용
  .github/dependabot.yml
Labels: ✨feature

#82 feature/#78 유저 리스트 페이징 조회 API 구현
  aics-api/src/main/java/kgu/developers/api/user/application/UserService.java
  aics-api/src/main/java/kgu/developers/api/user/presentation/UserController.java
  aics-api/src/main/java/kgu/developers/api/user/presentation/request/UserCreateRequest.java
  aics-api/src/main/java/kgu/developers/api/user/presentation/request/UserUpdateRequest.java
  aics-api/src/main/java/kgu/developers/api/user/presentation/response/UserDetailPageResponse.java
  aics-api/src/main/java/kgu/developers/api/user/presentation/response/UserDetailResponse.java
  aics-domain/src/main/java/kgu/developers/domain/user/domain/User.java
  aics-domain/src/main/java/kgu/developers/domain/user/domain/UserRepository.java
  aics-domain/src/main/java/kgu/developers/domain/user/infrastructure/JpaUserRepository.java
  aics-domain/src/main/java/kgu/developers/domain/user/infrastructure/QueryUserRepository.java
  aics-domain/src/main/java/kgu/developers/domain/user/infrastructure/UserRepositoryImpl.java
Labels: ✨feature

#87 chore/#86 dependabot 리뷰어 등록
  .github/dependabot.yml
Labels: 🔨refactor

#81 feature/#77 학과소개 CRU API 구현
  aics-api/src/main/java/kgu/developers/api/about/application/AboutService.java
  aics-api/src/main/java/kgu/developers/api/about/presentation/AboutController.java
  aics-api/src/main/java/kgu/developers/api/about/presentation/Exception/AboutExceptionCode.java
  aics-api/src/main/java/kgu/developers/api/about/presentation/Exception/AboutNotFoundException.java
  aics-api/src/main/java/kgu/developers/api/about/presentation/Exception/CategoryNotMatchException.java
  aics-api/src/main/java/kgu/developers/api/about/presentation/request/AboutRequest.java
  aics-api/src/main/java/kgu/developers/api/about/presentation/response/AboutPersistResponse.java
  aics-api/src/main/java/kgu/developers/api/about/presentation/response/AboutResponse.java
  aics-common/src/main/java/kgu/developers/common/config/SecurityConfig.java
  aics-domain/src/main/java/kgu/developers/domain/about/domain/About.java
  aics-domain/src/main/java/kgu/developers/domain/about/domain/AboutRepository.java
  aics-domain/src/main/java/kgu/developers/domain/about/infrastructure/AboutRepositoryImpl.java
  aics-domain/src/main/java/kgu/developers/domain/about/infrastructure/JpaAboutRepository.java
Labels: ✨feature

#89 refactor/#88 @Schema 예시 데이터 수정
  aics-api/src/main/java/kgu/developers/api/about/presentation/response/AboutPersistResponse.java
  aics-api/src/main/java/kgu/developers/api/about/presentation/response/AboutResponse.java
  aics-api/src/main/java/kgu/developers/api/auth/presentation/request/LoginRequest.java
  aics-api/src/main/java/kgu/developers/api/auth/presentation/response/TokenResponse.java
  aics-api/src/main/java/kgu/developers/api/comment/presentation/CommentController.java
  aics-api/src/main/java/kgu/developers/api/comment/presentation/request/CommentRequest.java
  aics-api/src/main/java/kgu/developers/api/comment/presentation/response/CommentListResponse.java
  aics-api/src/main/java/kgu/developers/api/comment/presentation/response/CommentPersistResponse.java
  aics-api/src/main/java/kgu/developers/api/comment/presentation/response/CommentResponse.java
  aics-api/src/main/java/kgu/developers/api/file/presentation/FileController.java
  aics-api/src/main/java/kgu/developers/api/file/presentation/response/FilePersistResponse.java
  aics-api/src/main/java/kgu/developers/api/file/presentation/response/FileResponse.java
  aics-api/src/main/java/kgu/developers/api/lab/presentation/LabController.java
  aics-api/src/main/java/kgu/developers/api/lab/presentation/request/LabRequest.java
  aics-api/src/main/java/kgu/developers/api/lab/presentation/response/LabDetailResponse.java
  aics-api/src/main/java/kgu/developers/api/lab/presentation/response/LabListResponse.java
  aics-api/src/main/java/kgu/developers/api/lab/presentation/response/LabPersistResponse.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/PostController.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/request/PostRequest.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/response/PostDetailResponse.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/response/PostPersistResponse.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/response/PostSummaryPageResponse.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/response/PostSummaryResponse.java
  aics-api/src/main/java/kgu/developers/api/professor/presentation/ProfessorController.java
  aics-api/src/main/java/kgu/developers/api/professor/presentation/request/ProfessorRequest.java
  aics-api/src/main/java/kgu/developers/api/professor/presentation/response/ProfessorListResponse.java
  aics-api/src/main/java/kgu/developers/api/professor/presentation/response/ProfessorPersistResponse.java
  aics-api/src/main/java/kgu/developers/api/professor/presentation/response/ProfessorResponse.java
  aics-api/src/main/java/kgu/developers/api/user/presentation/UserController.java
  aics-api/src/main/java/kgu/developers/api/user/presentation/response/UserDetailPageResponse.java
  aics-api/src/main/java/kgu/developers/api/user/presentation/response/UserDetailResponse.java
  aics-api/src/main/java/kgu/developers/api/user/presentation/response/UserPersistResponse.java
Labels: 🔨refactor

#91 chore/#90 pr요청 시 build CI workflow 작성
  .github/workflows/pull-request-build-check.yml
Labels: ✨feature

#95 feature/#92 회원가입 시 학과 검증 로직
  aics-domain/src/main/java/kgu/developers/domain/user/domain/DepartmentCodeCondition.java
  aics-domain/src/main/java/kgu/developers/domain/user/domain/User.java
  aics-domain/src/main/java/kgu/developers/domain/user/exception/DepartmentCodeNotValidException.java
  aics-domain/src/main/java/kgu/developers/domain/user/exception/EmailDomainNotValidException.java
  aics-domain/src/main/java/kgu/developers/domain/user/exception/UserDomainExceptionCode.java
  aics-domain/src/main/java/kgu/developers/domain/user/exception/UserNotFoundException.java
Labels: ✨feature, 🔨refactor

#97 feature/#96 coderabbit 적용
  .coderabbit.yaml
Labels: ✨feature, 🙋🏻‍♂️meeting

#94 refactor/#93 carousel 엔티티 text, link 컬럼 추가 및 lab, professor 조회 정렬 수정
  aics-api/src/main/java/kgu/developers/api/lab/application/LabService.java
  aics-api/src/main/java/kgu/developers/api/professor/application/ProfessorService.java
  aics-api/src/main/java/kgu/developers/api/professor/presentation/ProfessorController.java
  aics-api/src/main/java/kgu/developers/api/professor/presentation/request/ProfessorRequest.java
  aics-api/src/main/java/kgu/developers/api/professor/presentation/response/ProfessorResponse.java
  aics-domain/src/main/java/kgu/developers/domain/Carousel/domain/Carousel.java
  aics-domain/src/main/java/kgu/developers/domain/lab/domain/LabRepository.java
  aics-domain/src/main/java/kgu/developers/domain/lab/infrastructure/JpaLabRepository.java
  aics-domain/src/main/java/kgu/developers/domain/lab/infrastructure/LabRepositoryImpl.java
  aics-domain/src/main/java/kgu/developers/domain/professor/domain/Professor.java
  aics-domain/src/main/java/kgu/developers/domain/professor/domain/ProfessorRepository.java
  aics-domain/src/main/java/kgu/developers/domain/professor/domain/Role.java
  aics-domain/src/main/java/kgu/developers/domain/professor/infrastructure/JpaProfessorRepository.java
  aics-domain/src/main/java/kgu/developers/domain/professor/infrastructure/ProfessorRepositoryImpl.java
  aics-domain/src/main/java/kgu/developers/domain/professor/infrastructure/QueryProfessorRepository.java
Labels: 🔨refactor

#101 feature/#98 User 단위 및 통합 테스트코드 구현
  .coderabbit.yaml
  aics-api/build.gradle
  aics-api/src/main/java/kgu/developers/api/auth/application/AuthService.java
  aics-api/src/main/java/kgu/developers/api/auth/presentation/AuthController.java
  aics-api/src/main/java/kgu/developers/api/auth/presentation/request/LoginRequest.java
  aics-api/src/main/java/kgu/developers/api/user/application/UserService.java
  aics-api/src/main/java/kgu/developers/api/user/presentation/request/UserCreateRequest.java
  aics-api/src/main/java/kgu/developers/api/user/presentation/request/UserUpdateRequest.java
  aics-api/src/testFixtures/java/auth/application/AuthServiceTest.java
  aics-api/src/testFixtures/java/auth/presentation/AuthControllerTest.java
  aics-api/src/testFixtures/java/mock/TestContainer.java
  aics-api/src/testFixtures/java/user/application/UserServiceTest.java
  aics-api/src/testFixtures/java/user/presentation/UserControllerTest.java
  aics-common/src/main/java/kgu/developers/common/auth/jwt/JwtProperties.java
  aics-common/src/main/java/kgu/developers/common/auth/jwt/TokenProvider.java
  aics-domain/build.gradle
  aics-domain/src/main/java/kgu/developers/domain/user/domain/DeptCode.java
  aics-domain/src/main/java/kgu/developers/domain/user/domain/User.java
  aics-domain/src/main/java/kgu/developers/domain/user/exception/DepartmentCodeNotValidException.java
  aics-domain/src/main/java/kgu/developers/domain/user/exception/DeptCodeNotValidException.java
  aics-domain/src/main/java/kgu/developers/domain/user/exception/UserDomainExceptionCode.java
  aics-domain/src/testFixtures/java/mock/FakeUserRepository.java
  aics-domain/src/testFixtures/java/user/application/UserServiceTest.java
  aics-domain/src/testFixtures/java/user/domain/UserDomainTest.java
  build.gradle
Labels: ✨feature, dependencies

#104 fix/#103 JwtProperties 컴파일 에러 해결
  aics-common/src/main/java/kgu/developers/common/auth/jwt/JwtProperties.java
Labels: 🐞bug

#102 chore/#100 Github Actions, Docker를 이용한 CD
  .github/workflows/dev-build-deploy.yml
  .gitignore
  Dockerfile
Labels: ✨feature

#106 refactor/#105 게시글 생성, 조회 시 카테고리 컬럼 설정 추가
  aics-api/src/main/java/kgu/developers/api/post/application/PostService.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/PostController.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/response/PostDetailResponse.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/response/PostSummaryResponse.java
  aics-common/src/main/java/kgu/developers/common/exception/GlobalExceptionHandler.java
  aics-domain/src/main/java/kgu/developers/domain/post/domain/Post.java
  aics-domain/src/main/java/kgu/developers/domain/post/domain/PostRepository.java
  aics-domain/src/main/java/kgu/developers/domain/post/infrastructure/PostRepositoryImpl.java
  aics-domain/src/main/java/kgu/developers/domain/post/infrastructure/QueryPostRepository.java
Labels: 🔨refactor

#112 fix/#111 CD 워크플로 실행 버그 픽스
  .github/workflows/dev-build-deploy.yml
  aics-api/src/main/resources/application.yml
Labels: 🐞bug

#115 fix/#111 배포 스크립트 에러 수정
  .github/workflows/dev-build-deploy.yml
Labels: 🐞bug

#116 feature/#110 testfixtures 기반 professor testcode 구현
  aics-api/src/main/java/kgu/developers/api/professor/application/ProfessorService.java
  aics-api/src/main/java/kgu/developers/api/professor/presentation/ProfessorController.java
  aics-api/src/main/java/kgu/developers/api/professor/presentation/request/ProfessorRequest.java
  aics-api/src/testFixtures/java/professor/application/ProfessorServiceTest.java
  aics-api/src/testFixtures/java/professor/presentation/ProfessorControllerTest.java
  aics-domain/src/main/java/kgu/developers/domain/professor/domain/ProfessorRepository.java
  aics-domain/src/main/java/kgu/developers/domain/professor/infrastructure/ProfessorRepositoryImpl.java
  aics-domain/src/main/java/kgu/developers/domain/user/domain/User.java
  aics-domain/src/testFixtures/java/mock/FakeProfessorRepository.java
  aics-domain/src/testFixtures/java/professor/domain/ProfessorDomainTest.java
  aics-domain/src/testFixtures/java/user/domain/UserDomainTest.java
Labels: ✨feature

#117 feature/#109 Post 테스트 코드 작성
  aics-api/src/main/java/kgu/developers/api/post/application/PostService.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/request/PostRequest.java
  aics-api/src/testFixtures/java/post/application/PostServiceTest.java
  aics-api/src/testFixtures/java/post/presentation/PostControllerTest.java
  aics-domain/src/testFixtures/java/mock/FakePostRepository.java
  aics-domain/src/testFixtures/java/mock/TestEntityUtils.java
  aics-domain/src/testFixtures/java/post/application/PostServiceTest.java
  aics-domain/src/testFixtures/java/post/domain/PostDomainTest.java
Labels: ✨feature

#120 refactor/#119 에러 코드 문서화 작업 및 리팩토링
  aics-api/src/main/java/kgu/developers/api/about/presentation/Exception/AboutExceptionCode.java
  aics-api/src/main/java/kgu/developers/api/auth/application/AuthService.java
  aics-api/src/main/java/kgu/developers/api/auth/presentation/exception/AuthExceptionCode.java
  aics-api/src/main/java/kgu/developers/api/auth/presentation/exception/InvalidPasswordException.java
  aics-api/src/main/java/kgu/developers/api/comment/presentation/exception/CommentExceptionCode.java
  aics-api/src/main/java/kgu/developers/api/file/presentation/exception/FileExceptionCode.java
  aics-api/src/main/java/kgu/developers/api/lab/presentation/exception/LabExceptionCode.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/exception/PostExceptionCode.java
  aics-api/src/main/java/kgu/developers/api/professor/presentation/exception/ProfessorExceptionCode.java
  aics-api/src/main/java/kgu/developers/api/user/presentation/exception/UserExceptionCode.java
  aics-api/src/main/java/kgu/developers/api/user/presentation/exception/UserIdDuplicateException.java
  aics-api/src/testFixtures/java/auth/application/AuthServiceTest.java
  aics-domain/src/main/java/kgu/developers/domain/user/domain/User.java
  aics-domain/src/main/java/kgu/developers/domain/user/exception/InvalidPasswordException.java
  aics-domain/src/main/java/kgu/developers/domain/user/exception/UserDomainExceptionCode.java
  aics-domain/src/testFixtures/java/user/domain/UserDomainTest.java
Labels: ✨feature, 🔨refactor
