Repository kgu-developers/aics-server, pull requests merged in 2025-01, with the labels that each got.

#158 refactor/#157 토큰 만료 시간 조정
  aics-api/src/main/java/kgu/developers/api/auth/application/AuthService.java
  aics-domain/src/main/java/kgu/developers/domain/refreshtoken/domain/RefreshToken.java
Labels: 🔨refactor

#160 feature/#159 동아리 entity 설계 및 crud api 구현
  aics-admin/src/main/java/kgu/developers/admin/club/application/ClubAdminFacade.java
  aics-admin/src/main/java/kgu/developers/admin/club/presentation/ClubAdminController.java
  aics-admin/src/main/java/kgu/developers/admin/club/presentation/request/ClubRequest.java
  aics-admin/src/main/java/kgu/developers/admin/club/presentation/response/ClubPersistResponse.java
  aics-admin/src/main/resources/db/data.sql
  aics-admin/src/main/resources/db/schema.sql
  aics-api/src/main/java/kgu/developers/api/club/application/ClubFacade.java
  aics-api/src/main/java/kgu/developers/api/club/presentation/ClubController.java
  aics-api/src/main/java/kgu/developers/api/club/presentation/response/ClubDetailResponse.java
  aics-api/src/main/java/kgu/developers/api/club/presentation/response/ClubListResponse.java
  aics-api/src/main/java/kgu/developers/api/lab/application/LabFacade.java
  aics-api/src/main/java/kgu/developers/api/lab/presentation/response/LabDetailResponse.java
  aics-api/src/main/resources/db/data.sql
  aics-api/src/main/resources/db/schema.sql
  aics-api/src/testFixtures/java/club/application/ClubServiceTest.java
  aics-api/src/testFixtures/java/club/presentation/ClubControllerTest.java
  aics-common/src/main/java/kgu/developers/common/config/SecurityConfig.java
  aics-domain/src/main/java/kgu/developers/domain/club/application/command/ClubCommandService.java
  aics-domain/src/main/java/kgu/developers/domain/club/application/query/ClubQueryService.java
  aics-domain/src/main/java/kgu/developers/domain/club/domain/Club.java
  aics-domain/src/main/java/kgu/developers/domain/club/domain/ClubRepository.java
  aics-domain/src/main/java/kgu/developers/domain/club/exception/ClubDomainExceptionCode.java
  aics-domain/src/main/java/kgu/developers/domain/club/exception/ClubNotFoundException.java
  aics-domain/src/main/java/kgu/developers/domain/club/infrastructure/ClubRepositoryImpl.java
  aics-domain/src/main/java/kgu/developers/domain/club/infrastructure/JpaClubRepository.java
  aics-domain/src/testFixtures/java/club/application/ClubServiceTest.java
  aics-domain/src/testFixtures/java/club/domain/ClubDomainTest.java
  aics-domain/src/testFixtures/java/comment/domain/CommentDomainTest.java
  aics-domain/src/testFixtures/java/post/domain/PostDomainTest.java
  aics-domain/src/testFixtures/java/user/domain/UserDomainTest.java
Labels: ✨feature

#161 refactor/#156 api 인가처리
  aics-admin/src/main/java/kgu/developers/admin/about/presentation/AboutAdminController.java
  aics-admin/src/main/java/kgu/developers/admin/club/presentation/ClubAdminController.java
  aics-admin/src/main/java/kgu/developers/admin/comment/presentation/CommentAdminController.java
  aics-admin/src/main/java/kgu/developers/admin/file/presentation/FileAdminController.java
  aics-admin/src/main/java/kgu/developers/admin/lab/presentation/LabAdminController.java
  aics-admin/src/main/java/kgu/developers/admin/post/presentation/PostAdminController.java
  aics-admin/src/main/java/kgu/developers/admin/professor/presentation/ProfessorAdminController.java
  aics-admin/src/main/java/kgu/developers/admin/user/presentation/UserAdminController.java
  aics-api/src/main/java/kgu/developers/api/auth/application/AuthService.java
  aics-common/src/main/java/kgu/developers/common/auth/jwt/TokenProvider.java
  aics-common/src/main/java/kgu/developers/common/config/SecurityConfig.java
  aics-common/src/main/java/kgu/developers/common/domain/BaseRole.java
  aics-common/src/main/java/kgu/developers/common/exception/AdminExceptionCode.java
  aics-common/src/main/java/kgu/developers/common/exception/GlobalExceptionHandler.java
  aics-domain/src/main/java/kgu/developers/domain/user/application/response/UserDetailResponse.java
  aics-domain/src/main/java/kgu/developers/domain/user/domain/User.java
Labels: 🔨refactor

#166 refactor/#163 교수 응답 QA
  aics-admin/src/main/java/kgu/developers/admin/professor/application/ProfessorAdminFacade.java
  aics-admin/src/main/java/kgu/developers/admin/professor/presentation/request/ProfessorRequest.java
  aics-api/src/main/java/kgu/developers/api/professor/presentation/response/ProfessorListResponse.java
  aics-api/src/main/resources/db/data.sql
  aics-api/src/main/resources/db/schema.sql
  aics-domain/src/main/java/kgu/developers/domain/professor/application/command/ProfessorCommandService.java
  aics-domain/src/main/java/kgu/developers/domain/professor/application/response/ProfessorResponse.java
  aics-domain/src/main/java/kgu/developers/domain/professor/domain/Professor.java
  aics-domain/src/testFixtures/java/professor/domain/ProfessorDomainTest.java
Labels: 🔨refactor

#165 refactor/#162 연구실 엔티티 Response 필드 관련 QA fix
  aics-admin/src/main/java/kgu/developers/admin/file/presentation/FileAdminController.java
  aics-admin/src/main/java/kgu/developers/admin/lab/application/LabAdminFacade.java
  aics-admin/src/main/java/kgu/developers/admin/lab/presentation/request/LabRequest.java
  aics-api/src/main/java/kgu/developers/api/lab/presentation/response/LabDetailResponse.java
  aics-api/src/main/java/kgu/developers/api/lab/presentation/response/LabListResponse.java
  aics-api/src/main/resources/db/data.sql
  aics-api/src/main/resources/db/schema.sql
  aics-domain/src/main/java/kgu/developers/domain/file/domain/FileDomain.java
  aics-domain/src/main/java/kgu/developers/domain/lab/application/command/LabCommandService.java
  aics-domain/src/main/java/kgu/developers/domain/lab/domain/Lab.java
  aics-domain/src/testFixtures/java/lab/domain/LabDomainTest.java
Labels: 🔨refactor

#167 refactor/#151 Controller 추상화 Swagger와 구현체를 분리
  .github/workflows/pull-request-test-coverage.yml
  aics-admin/src/main/java/kgu/developers/admin/about/application/AboutAdminFacade.java
  aics-admin/src/main/java/kgu/developers/admin/about/presentation/AboutAdminController.java
  aics-admin/src/main/java/kgu/developers/admin/about/presentation/AboutAdminControllerImpl.java
  aics-admin/src/main/java/kgu/developers/admin/about/presentation/request/AboutCreateRequest.java
  aics-admin/src/main/java/kgu/developers/admin/club/presentation/ClubAdminController.java
  aics-admin/src/main/java/kgu/developers/admin/club/presentation/ClubAdminControllerImpl.java
  aics-admin/src/main/java/kgu/developers/admin/comment/presentation/CommentAdminController.java
  aics-admin/src/main/java/kgu/developers/admin/comment/presentation/CommentAdminControllerImpl.java
  aics-admin/src/main/java/kgu/developers/admin/config/SwaggerConfig.java
  aics-admin/src/main/java/kgu/developers/admin/file/presentation/FileAdminController.java
  aics-admin/src/main/java/kgu/developers/admin/file/presentation/FileAdminControllerImpl.java
  aics-admin/src/main/java/kgu/developers/admin/lab/presentation/LabAdminController.java
  aics-admin/src/main/java/kgu/developers/admin/lab/presentation/LabAdminControllerImpl.java
  aics-admin/src/main/java/kgu/developers/admin/post/presentation/PostAdminController.java
  aics-admin/src/main/java/kgu/developers/admin/post/presentation/PostAdminControllerImpl.java
  aics-admin/src/main/java/kgu/developers/admin/professor/presentation/ProfessorAdminController.java
  aics-admin/src/main/java/kgu/developers/admin/professor/presentation/ProfessorAdminControllerImpl.java
  aics-admin/src/main/java/kgu/developers/admin/user/presentation/UserAdminController.java
  aics-admin/src/main/java/kgu/developers/admin/user/presentation/UserAdminControllerImpl.java
  aics-admin/src/main/resources/application.yml
  aics-api/src/main/java/kgu/developers/api/about/presentation/AboutController.java
  aics-api/src/main/java/kgu/developers/api/about/presentation/AboutControllerImpl.java
  aics-api/src/main/java/kgu/developers/api/auth/presentation/AuthController.java
  aics-api/src/main/java/kgu/developers/api/auth/presentation/AuthControllerImpl.java
  aics-api/src/main/java/kgu/developers/api/club/presentation/ClubController.java
  aics-api/src/main/java/kgu/developers/api/club/presentation/ClubControllerImpl.java
  aics-api/src/main/java/kgu/developers/api/comment/presentation/CommentController.java
  aics-api/src/main/java/kgu/developers/api/comment/presentation/CommentControllerImpl.java
  aics-api/src/main/java/kgu/developers/api/config/SwaggerConfig.java
  aics-api/src/main/java/kgu/developers/api/lab/presentation/LabController.java
  aics-api/src/main/java/kgu/developers/api/lab/presentation/LabControllerImpl.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/PostController.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/PostControllerImpl.java
  aics-api/src/main/java/kgu/developers/api/professor/presentation/ProfessorController.java
  aics-api/src/main/java/kgu/developers/api/professor/presentation/ProfessorControllerImpl.java
  aics-api/src/main/java/kgu/developers/api/user/presentation/UserController.java
  aics-api/src/main/java/kgu/developers/api/user/presentation/UserControllerImpl.java
  aics-api/src/main/resources/application.yml
  aics-api/src/main/resources/db/data.sql
  aics-api/src/main/resources/db/schema.sql
  aics-api/src/testFixtures/java/auth/presentation/AuthControllerTest.java
  aics-api/src/testFixtures/java/mock/TestContainer.java
  aics-common/src/main/java/kgu/developers/common/exception/GlobalExceptionHandler.java
  aics-domain/src/main/java/kgu/developers/domain/post/domain/Category.java
  codecov.yml
Labels: 🔨refactor

#169 fix/#168 개발 서버 Swagger에서 ip가 표기되지 않는 버그 픽스
  aics-admin/src/main/java/kgu/developers/admin/config/SwaggerConfig.java
  aics-admin/src/main/resources/application-dev.yml
  aics-admin/src/main/resources/application-local.yml
  aics-admin/src/main/resources/application.yml
  aics-api/src/main/java/kgu/developers/api/config/SwaggerConfig.java
  aics-api/src/main/resources/application-dev.yml
  aics-api/src/main/resources/application-local.yml
  aics-api/src/main/resources/application.yml
Labels: 🐞bug

#171 fix/#170 schema.sql의 DDL 실행시 에러 발생 픽스
  aics-api/src/main/resources/db/schema.sql
Labels: 🐞bug
