Repository kgu-developers/aics-server, pull requests merged in 2025-02, with the labels that each got.

#180 docs/#179 리드미 추가
  .github/workflows/pull-request-test-coverage.yml
  LICENSE
  README.md
  images/application_architecture.png
  images/system_architecture.png
Labels: ✨feature

#184 fix/#183 LabDetailResponse 이미지 필드명 수정 및 연구실 저장 BL 개선
  README.md
  aics-admin/src/main/java/kgu/developers/admin/lab/application/LabAdminFacade.java
  aics-admin/src/main/java/kgu/developers/admin/lab/presentation/LabAdminController.java
  aics-admin/src/main/java/kgu/developers/admin/lab/presentation/LabAdminControllerImpl.java
  aics-admin/src/testFixtures/java/lab/application/LabAdminFacadeTest.java
  aics-api/src/main/java/kgu/developers/api/lab/presentation/response/LabDetailResponse.java
  aics-api/src/main/java/kgu/developers/api/lab/presentation/response/LabListResponse.java
  aics-domain/src/main/java/kgu/developers/domain/lab/application/command/LabCommandService.java
  aics-domain/src/main/java/kgu/developers/domain/lab/domain/Lab.java
  aics-domain/src/testFixtures/java/lab/application/LabCommandServiceTest.java
  aics-domain/src/testFixtures/java/lab/application/LabQueryServiceTest.java
  aics-domain/src/testFixtures/java/lab/domain/LabDomainTest.java
  aics-domain/src/testFixtures/java/mock/FakeTestContainer.java
  aics-domain/src/testFixtures/java/mock/TestContainer.java
Labels: 🐞bug, 🔨refactor

#188 refactor/#182 about 엔티티 단순화
  aics-admin/src/main/java/kgu/developers/admin/about/application/AboutAdminFacade.java
  aics-admin/src/main/java/kgu/developers/admin/about/presentation/request/AboutCreateRequest.java
  aics-admin/src/testFixtures/java/about/application/AboutAdminFacadeTest.java
  aics-api/src/main/java/kgu/developers/api/about/application/AboutFacade.java
  aics-api/src/main/java/kgu/developers/api/about/presentation/AboutController.java
  aics-api/src/main/java/kgu/developers/api/about/presentation/AboutControllerImpl.java
  aics-api/src/main/java/kgu/developers/api/about/presentation/response/AboutResponse.java
  aics-api/src/main/resources/db/data.sql
  aics-api/src/main/resources/db/schema.sql
  aics-api/src/testFixtures/java/about/application/AboutFacadeTest.java
  aics-domain/src/main/java/kgu/developers/domain/about/application/command/AboutCommandService.java
  aics-domain/src/main/java/kgu/developers/domain/about/application/query/AboutQueryService.java
  aics-domain/src/main/java/kgu/developers/domain/about/domain/About.java
  aics-domain/src/main/java/kgu/developers/domain/about/domain/AboutRepository.java
  aics-domain/src/main/java/kgu/developers/domain/about/domain/Category.java
  aics-domain/src/main/java/kgu/developers/domain/about/domain/SubCategory.java
  aics-domain/src/main/java/kgu/developers/domain/about/infrastructure/AboutRepositoryImpl.java
  aics-domain/src/main/java/kgu/developers/domain/about/infrastructure/JpaAboutRepository.java
  aics-domain/src/testFixtures/java/about/application/AboutCommandServiceTest.java
  aics-domain/src/testFixtures/java/about/application/AboutQueryServiceTest.java
  aics-domain/src/testFixtures/java/about/domain/AboutDomainTest.java
  aics-domain/src/testFixtures/java/mock/repository/FakeAboutRepository.java
Labels: 🔨refactor

#190 refactor/#186 docker-compose.yml Github 연동 및 Auth 모듈 추가에 따른 배포 파이프라인 수정
  .github/workflows/dev-build-deploy.yml
  .gitignore
  docker/development/docker-compose.yml
  docker/production/.gitkeep
Labels: 🔨refactor

#192 fix/#191 Docker build 실패 버그 수정
  .github/workflows/dev-build-deploy.yml
  aics-admin/src/main/java/kgu/developers/admin/config/SwaggerConfig.java
  aics-admin/src/main/resources/application-dev.yml
  aics-admin/src/main/resources/application-local.yml
  aics-admin/src/main/resources/application.yml
  aics-api/src/main/java/kgu/developers/api/config/SwaggerConfig.java
  aics-api/src/main/resources/application-dev.yml
  aics-api/src/main/resources/application-local.yml
  aics-api/src/main/resources/application.yml
  aics-auth/Dockerfile
  aics-auth/src/main/java/kgu/developers/auth/config/SwaggerConfig.java
  aics-auth/src/main/resources/application-dev.yml
  aics-auth/src/main/resources/application-local.yml
  aics-auth/src/main/resources/application.yml
  aics-common/src/main/java/kgu/developers/common/config/SecurityConfig.java
  docker/development/docker-compose.yml
Labels: 🐞bug

#196 feature/#189 첨부파일 저장 경로 변경
  aics-admin/src/main/java/kgu/developers/admin/file/application/FileAdminFacade.java
  aics-admin/src/main/java/kgu/developers/admin/file/presentation/FileAdminController.java
  aics-admin/src/main/java/kgu/developers/admin/file/presentation/FileAdminControllerImpl.java
  aics-domain/src/main/java/kgu/developers/domain/file/infrastructure/FileStorageService.java
  aics-domain/src/main/java/kgu/developers/domain/file/infrastructure/FileStorageServiceImpl.java
Labels: 🔨refactor

#195 feature/#194 게시글 API 프론트 QA 반영
  aics-admin/src/main/java/kgu/developers/admin/post/application/PostAdminFacade.java
  aics-admin/src/main/java/kgu/developers/admin/post/presentation/PostAdminController.java
  aics-admin/src/main/java/kgu/developers/admin/post/presentation/PostAdminControllerImpl.java
  aics-admin/src/main/java/kgu/developers/admin/post/presentation/request/PostRequest.java
  aics-admin/src/testFixtures/java/post/application/PostAdminFacadeTest.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/response/PostSummaryPageResponse.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/response/PostSummaryResponse.java
  aics-api/src/testFixtures/java/comment/application/CommentFacadeTest.java
  aics-api/src/testFixtures/java/post/application/PostFacadeTest.java
  aics-domain/src/main/java/kgu/developers/domain/file/application/query/FileQueryService.java
  aics-domain/src/main/java/kgu/developers/domain/post/application/command/PostCommandService.java
  aics-domain/src/main/java/kgu/developers/domain/post/domain/Post.java
  aics-domain/src/testFixtures/java/comment/application/CommentCommandServiceTest.java
  aics-domain/src/testFixtures/java/comment/application/CommentQueryServiceTest.java
  aics-domain/src/testFixtures/java/comment/domain/CommentDomainTest.java
  aics-domain/src/testFixtures/java/mock/FakeTestContainer.java
  aics-domain/src/testFixtures/java/mock/TestContainer.java
  aics-domain/src/testFixtures/java/post/application/PostCommandServiceTest.java
  aics-domain/src/testFixtures/java/post/application/PostQueryServiceTest.java
  aics-domain/src/testFixtures/java/post/domain/PostDomainTest.java
Labels: ✨feature

#193 feature/#185 image resizing 기능 구현
  .gitignore
  aics-api/src/main/resources/db/data.sql
  aics-api/src/main/resources/db/schema.sql
  aics-domain/src/main/java/kgu/developers/domain/file/infrastructure/FileStorageServiceImpl.java
  aics-domain/src/main/java/kgu/developers/domain/file/infrastructure/ImageResizingService.java
  aics-domain/src/main/java/kgu/developers/domain/file/infrastructure/ImageResizingServiceImpl.java
  build.gradle
Labels: ✨feature

#200 fix: cors 이슈 픽스
  aics-common/src/main/java/kgu/developers/common/config/SecurityConfig.java
Labels: 🐞bug

#209 refactor/#208 키워드 리스트 조회로 수정
  aics-api/src/main/java/kgu/developers/api/post/application/PostFacade.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/PostController.java
  aics-api/src/main/java/kgu/developers/api/post/presentation/PostControllerImpl.java
  aics-api/src/testFixtures/java/post/application/PostFacadeTest.java
  aics-domain/src/main/java/kgu/developers/domain/post/application/query/PostQueryService.java
  aics-domain/src/main/java/kgu/developers/domain/post/domain/PostRepository.java
  aics-domain/src/main/java/kgu/developers/domain/post/infrastructure/PostRepositoryImpl.java
  aics-domain/src/main/java/kgu/developers/domain/post/infrastructure/QueryPostRepository.java
  aics-domain/src/testFixtures/java/mock/repository/FakePostRepository.java
  aics-domain/src/testFixtures/java/post/application/PostQueryServiceTest.java
Labels: 🔨refactor

#207 refactor/#203 유저 목록 조회 이름 검색 기능 추가
  aics-admin/src/main/java/kgu/developers/admin/user/application/UserAdminFacade.java
  aics-admin/src/main/java/kgu/developers/admin/user/presentation/UserAdminController.java
  aics-admin/src/main/java/kgu/developers/admin/user/presentation/UserAdminControllerImpl.java
  aics-admin/src/testFixtures/java/user/application/UserAdminFacadeTest.java
  aics-domain/src/main/java/kgu/developers/domain/user/application/query/UserQueryService.java
  aics-domain/src/main/java/kgu/developers/domain/user/domain/UserRepository.java
  aics-domain/src/main/java/kgu/developers/domain/user/infrastructure/QueryUserRepository.java
  aics-domain/src/main/java/kgu/developers/domain/user/infrastructure/UserRepositoryImpl.java
  aics-domain/src/testFixtures/java/mock/repository/FakeUserRepository.java
  aics-domain/src/testFixtures/java/user/application/UserQueryServiceTest.java
Labels: 🔨refactor
